/**
 * Curated iteration log. Append new entries at the top: every functional
 * iteration (a new skill, plugin, or core-module change) adds one entry in
 * the same change set, so the Settings timeline and the codebase iterate
 * together. Entries carry bilingual titles and Markdown details; the
 * timeline renders the active locale's copy.
 */

import type { IterationLogEntry } from './model.ts'

export const ENTRIES: readonly IterationLogEntry[] = [
  {
    id: '2026-08-18-google-live-discovery',
    date: '2026-08-18',
    kind: 'feature',
    scope: 'local',
    title: 'Google 实时发现与模型全选',
    titleEn: 'Google live discovery and model select-all',
    detail: '本地模型选择支持 Google 实时发现（live discovery）与一键全选，并完成模型 UI 自定义；本地内核同步至 v0.1.0-rc.7（`feat(local): Google live discovery, model select-all, and model UI customizations`）。',
    detailEn: 'Local model picking gains Google live discovery and a select-all toggle, plus model-UI customizations; the local kernel is synced to v0.1.0-rc.7 (`feat(local): Google live discovery, model select-all, and model UI customizations`).',
  },
  {
    id: '2026-08-18-model-image-input',
    date: '2026-08-18',
    kind: 'feature',
    scope: 'local',
    title: '模型设置图片输入开关',
    titleEn: 'Image-input switches in model settings',
    detail: '`ui-settings-models` 完成模型选择器的图片输入开关（image-input），模型选择、测试与文档在同一变更集内补齐（`feat(ui-settings-models): finish image-input switches — model picker, tests, docs`）。',
    detailEn: '`ui-settings-models` finishes the model picker image-input switches, with picker, tests, and docs in the same change set (`feat(ui-settings-models): finish image-input switches — model picker, tests, docs`).',
  },
  {
    id: '2026-08-17-release-rc7',
    date: '2026-08-17',
    version: '0.1.0-rc.7',
    kind: 'feature',
    scope: 'system',
    title: '发布 0.1.0-rc.7',
    titleEn: 'Release 0.1.0-rc.7',
    detail: 'dsh 家族发布 `0.1.0-rc.7`，整合此前多轮修复、性能与文档改进（`release(dsh): 0.1.0-rc.7`）。',
    detailEn: 'The dsh family ships `0.1.0-rc.7`, bundling the fixes, performance, and doc improvements of the past days (`release(dsh): 0.1.0-rc.7`).',
  },
  {
    id: '2026-08-15-pty-prompt',
    date: '2026-08-15',
    kind: 'fix',
    scope: 'system',
    title: '常驻 bash 更快稳定',
    titleEn: 'Persistent bash settles fast',
    detail: '终端工具在常驻 bash 会话上保留受控提示符（controlled prompt），使会话快速稳定、不再挂起（`fix(pty): keep the controlled prompt so persistent bash settles fast`）。',
    detailEn: 'The terminal tool keeps the controlled prompt on persistent bash sessions so they settle fast instead of hanging (`fix(pty): keep the controlled prompt so persistent bash settles fast`).',
  },
  {
    id: '2026-08-15-llm-replay',
    date: '2026-08-15',
    kind: 'fix',
    scope: 'system',
    title: '回放状态与组装内容对齐',
    titleEn: 'Replay state aligned with assembled content',
    detail: '修复回放（replay）时状态与已组装内容不一致的问题，不可用状态改为优雅降级（`fix(llm): align replay state with assembled content and degrade unusable state`）。',
    detailEn: 'Replay state now aligns with assembled content, and unusable states degrade gracefully instead of surfacing stale data (`fix(llm): align replay state with assembled content and degrade unusable state`).',
  },
  {
    id: '2026-08-15-web-preload',
    date: '2026-08-15',
    kind: 'core',
    scope: 'system',
    title: '移除 module preload polyfill',
    titleEn: 'Drop the module preload polyfill',
    detail: 'Web 端移除 module preload polyfill，削减启动开销（`perf(web): remove the module preload polyfill`）。',
    detailEn: 'The web client drops the module preload polyfill, trimming startup overhead (`perf(web): remove the module preload polyfill`).',
  },
  {
    id: '2026-08-14-low-reasoning',
    date: '2026-08-14',
    kind: 'feature',
    scope: 'system',
    title: 'DeepSeek 低推理强度支持',
    titleEn: 'Low reasoning effort for DeepSeek',
    detail: '`llm-deepseek` 提供方支持低推理强度（low reasoning effort）选项，可在不需要完整深度时降低延迟与成本（`feat(llm-deepseek): support low reasoning effort`）。',
    detailEn: 'The `llm-deepseek` provider supports a low reasoning-effort option for lower latency and cost when full depth is not needed (`feat(llm-deepseek): support low reasoning effort`).',
  },
  {
    id: '2026-08-14-ptc-mode',
    date: '2026-08-14',
    kind: 'fix',
    scope: 'system',
    title: 'Code 预设更名为 PTC Mode',
    titleEn: 'Code preset renamed to PTC Mode',
    detail: '代理预设中的 Code 模式更名为 PTC Mode，并在 UI 中统一为句首大写标题（`fix(ui-agent-preset): rename code preset to PTC Mode`）。',
    detailEn: 'The Code agent preset is renamed to PTC Mode, with sentence-case titles across the UI (`fix(ui-agent-preset): rename code preset to PTC Mode`).',
  },
  {
    id: '2026-08-13-session-corruption',
    date: '2026-08-13',
    kind: 'fix',
    scope: 'system',
    title: '会话持久化损坏恢复',
    titleEn: 'Session persistence corruption recovery',
    detail: '修复会话持久化损坏错误（`SessionPersistenceCorruptionError`），加载损坏会话时不再崩溃（`fix: SessionPersistenceCorruptionError`）。',
    detailEn: 'Session-persistence corruption errors are contained so loading a corrupted session no longer crashes the app (`fix: SessionPersistenceCorruptionError`).',
  },
  {
    id: '2026-08-13-dashscope-vl-model',
    date: '2026-08-13',
    kind: 'feature',
    scope: 'local',
    title: '配置 Qwen VL 模型（原生拖图通道）',
    titleEn: 'Qwen VL models configured (native image attachments)',
    detail: '通过 `llm-pi-ai` 设置段注册 DashScope 提供方（OpenAI 兼容端点），加入 `qwen3.7-plus` / `qwen3-vl-plus` / `qwen3-vl-flash` 三个视觉模型，凭据写入 `~/.dsh/.credentials.yaml`。会话中选中这些模型后，输入框的拖图/粘贴通道即可原生使用；不选时仍走 Qwen MCP 工具路径。',
    detailEn: 'A DashScope provider (OpenAI-compatible endpoint) is registered through the `llm-pi-ai` settings section with `qwen3.7-plus` / `qwen3-vl-plus` / `qwen3-vl-flash`; the credential lives in `~/.dsh/.credentials.yaml`. Selecting one of these models in a session unlocks the native composer image path; other sessions keep using the Qwen MCP tools.',
  },
  {
    id: '2026-08-13-iteration-log',
    date: '2026-08-13',
    kind: 'feature',
    scope: 'system',
    title: '新增「迭代日志」设置页',
    titleEn: 'New iteration-log settings section',
    detail: '设置面板新增迭代日志时间线：按时间倒序展示功能、技能、插件、核心模块与修复的迭代记录，支持类型/范围筛选与搜索。日志与代码库同仓库维护，迭代即记录。',
    detailEn: 'The settings panel gains an iteration-log timeline: features, skills, plugins, core-module changes, and fixes in newest-first order, with kind/scope filters and search. The log lives in the repository, so iterating and recording happen in the same change set.',
  },
  {
    id: '2026-08-13-qwen-mm-plugins-plugin',
    date: '2026-08-13',
    kind: 'plugin',
    scope: 'local',
    title: '接入 Qwen-MM-Plugins（识图与视频理解）',
    titleEn: 'Qwen-MM-Plugins integration (image & video understanding)',
    detail: '通过 `dsh-mcp-client` 注册 `qwen-mm-plugins-api` 能力（tag `qwen-mm-plugins-api-v1.0.3`），获得 12 个 MCP 工具：`vision_chat` / `ocr` / `grounding`（识图）、`omni_av_caption` / `omni_av_grounding` / `omni_av_counting` / 多说话人 ASR（视频与音频理解）。视觉推理在 Qwen 云端完成，本机模型负责调度与文本推理；已附带安装 uv 与 ffmpeg/ffprobe。',
    detailEn: 'The `qwen-mm-plugins-api` capability (tag `qwen-mm-plugins-api-v1.0.3`) is registered through `dsh-mcp-client`, exposing 12 MCP tools: `vision_chat` / `ocr` / `grounding` for images, and `omni_av_caption` / `omni_av_grounding` / `omni_av_counting` / multi-speaker ASR for video and audio. Vision runs on Qwen cloud models while the local model orchestrates tools and reasons over the returned text; uv and ffmpeg/ffprobe were installed alongside.',
  },
  {
    id: '2026-08-13-qwen-mm-plugins-skill',
    date: '2026-08-13',
    kind: 'skill',
    scope: 'local',
    title: '安装 qwen-mm-plugins-api 技能',
    titleEn: 'Installed the qwen-mm-plugins-api skill',
    detail: '技能目录新增 `qwen-mm-plugins-api`（来自 Qwen-MM-Plugins v1.0.3）：指导模型在图像/视频/音频问题出现时选择正确的 VL / Omni 工具与模型，避免与本地 ffmpeg 脚本重叠。',
    detailEn: 'The `qwen-mm-plugins-api` skill (from Qwen-MM-Plugins v1.0.3) is installed: it guides tool and model selection for image/video/audio questions across the VL and Omni families, avoiding overlap with manual ffmpeg scripting.',
  },
  {
    id: '2026-08-13-npm-public',
    date: '2026-08-13',
    version: '0.1.0-rc.5',
    kind: 'feature',
    scope: 'system',
    title: '发布 0.1.0-rc.5 并公开 npm 发布',
    titleEn: 'Release 0.1.0-rc.5 and public npm publishing',
    detail: 'dsh 家族包完成公开发布流程（`build(release): publish the dsh family publicly`）；本版本同步包含英文引导文案补全与 README 双语校对。',
    detailEn: 'The dsh package family completes its public publishing flow (`build(release): publish the dsh family publicly`); this release also ships the English onboarding copy and the bilingual README review.',
  },
  {
    id: '2026-08-13-onboarding-en',
    date: '2026-08-13',
    kind: 'fix',
    scope: 'system',
    title: '补全英文引导文案',
    titleEn: 'English onboarding copy',
    detail: '引导流程（onboarding）补齐英语文案分支，并补上相应测试覆盖（`fix(web): add English onboarding copy`）。',
    detailEn: 'The onboarding flow gains its English copy branch with matching test coverage (`fix(web): add English onboarding copy`).',
  },
  {
    id: '2026-08-13-newest-first',
    date: '2026-08-13',
    kind: 'fix',
    scope: 'system',
    title: '会话列表默认最新优先',
    titleEn: 'Newest sessions first by default',
    detail: '工作区侧栏的会话列表默认按最新排序，不再需要手动切换（`fix(web): show newest sessions first by default`）。',
    detailEn: 'The workspace session list now sorts newest-first by default instead of requiring a manual switch (`fix(web): show newest sessions first by default`).',
  },
  {
    id: '2026-08-13-wildcard-host',
    date: '2026-08-13',
    kind: 'core',
    scope: 'system',
    title: 'Web 通配符主机信任加固',
    titleEn: 'Web wildcard-host trust hardening',
    detail: '收紧 Web 服务的通配符主机信任判定，LAN 暴露面按绑定地址与受信主机精确推导（`fix(web): address wildcard host review`）。',
    detailEn: 'Wildcard host trust for the web server is tightened: the LAN exposure surface is now derived precisely from the bound address and trusted hosts (`fix(web): address wildcard host review`).',
  },
]
